default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: testing_development
  user: postgres
  host: db

test:
  <<: *default
  database: testing_test
  user: postgres
  host: db

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>